name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy using SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          'cd /home/experiments/Bomberman/bomberman-client && git pull https://${{secrets.GIT_USER}}:${{secrets.GIT_PAT}}@github.com/${{secrets.GIT_USER}}/bomberman-client.git master && npm ic && npm run build'