name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10.0  # Replace with your desired Node.js version

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy using SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          cd /home/experiments/Bomberman/bomberman-client; \
          git pull; \
          npm install; \
          npm run build; \